### PR TITLE
Update login form to submit on pressing enter

### PR DESCRIPTION
**Pull request by matthewmcgarvey**
Just changing `<div>` to `<form>` to allow submitting log in with enter. The rest is mint's formatter changes.

### CODE REVIEW

**Comment by kingsleyh** [comment]
Great thanks - I will take a look today

**Comment by kingsleyh** [comment]
sorry not had a chance to look yet - but will do very soon. Also I'm planning the next set of work for this app as well so I will put them as issues with explanations also

**Comment by kingsleyh** [comment]
ok - had a look. I spotted a problem when the user puts the incorrect password - the error message shows for a second and then the page reloads and loses the message.

I don't think I like the form approach - I would prefer to add an onEnter handler to the password input - which would avoid the default submit behaviour.

**Comment by kingsleyh** [comment]
I've implemented a re-usable submitOnEnter so I'm going to close this one.

see: https://github.com/Axentro/xentro/blob/master/source/modules/UiHelper.mint#L32
and it's usage here: https://github.com/Axentro/xentro/blob/master/source/pages/Login.mint#L104

**Comment by matthewmcgarvey** [comment]
@kingsleyh I realized what I messed up here while working on a separate project. The form has an `onSubmit` property that can be given a function. That could be where the log in stuff happens but the first thing you do is prevent the default event behavior. Here's mint's example https://github.com/mint-lang/mint-realworld/blob/ce19f133470671bacb549f10a397246f66d7cc10/source/Components/Input.mint#L167

**Pull request closed without merging**
